server.port=8081
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/annraksh
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update